#!/bin/bash
# Model Registry Cleanup Script
# 
# Removes old model versions from the registry while preserving:
#   - current_version (actively deployed)
#   - previous_version (for rollback)
#   - N most recent versions (configurable retention)
#
# Runs as a systemd timer on the primary_datasink to manage registry disk usage.
# Generated by Ansible template
#
# Configuration:
#   REGISTRY_PATH: {{ sentinelcam_model_registry }}
#   RETENTION_COUNT: {{ sentinelcam_model_retention }} (versions to keep)
#   LOG_FILE: {{ sentinelcam_data_path }}/logs/model_cleanup.log
#
# Logs all cleanup operations with timestamps and removed versions.

set -e
set -o pipefail

# Configuration
REGISTRY_PATH="{{ sentinelcam_model_registry }}"
RETENTION_COUNT={{ sentinelcam_model_retention }}
ANSIBLE_DIR="{{ sentinelcam_deployment_source }}/devops/ansible"
LOG_FILE="{{ sentinelcam_data_path }}/logs/model_cleanup.log"
REGISTRY_CONFIG="${ANSIBLE_DIR}/inventory/group_vars/all/model_registry.yaml"

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")"

# Logging function
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "===== Model registry cleanup started ====="
log "Registry path: ${REGISTRY_PATH}"
log "Retention count: ${RETENTION_COUNT}"

# Validate registry exists
if [ ! -d "$REGISTRY_PATH" ]; then
    log "ERROR: Registry path does not exist: ${REGISTRY_PATH}"
    exit 1
fi

# Validate registry config exists
if [ ! -f "$REGISTRY_CONFIG" ]; then
    log "ERROR: Registry config not found: ${REGISTRY_CONFIG}"
    exit 1
fi

# Extract current and previous versions from registry config
get_protected_versions() {
    local model_name="$1"
    grep -A2 "^  ${model_name}:" "$REGISTRY_CONFIG" | \
        grep -E '(current_version|previous_version):' | \
        awk '{print $2}' | \
        tr -d '"' | \
        grep -v '^null$' || true
}

# Process each model directory
TOTAL_REMOVED=0
TOTAL_SIZE_FREED=0

for model_dir in "${REGISTRY_PATH}"/*; do
    if [ ! -d "$model_dir" ]; then
        continue
    fi
    
    model_name=$(basename "$model_dir")
    log ""
    log "Processing model: ${model_name}"
    
    # Get protected versions (current + previous)
    protected_versions=$(get_protected_versions "$model_name")
    log "  Protected versions: ${protected_versions:-none}"
    
    # Get all version directories sorted by date (newest first)
    versions=()
    while IFS= read -r -d '' version_dir; do
        versions+=("$(basename "$version_dir")")
    done < <(find "$model_dir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -zr)
    
    version_count=${#versions[@]}
    log "  Total versions: ${version_count}"
    
    if [ $version_count -le $((RETENTION_COUNT + 2)) ]; then
        log "  Skipping: version count within retention limits"
        continue
    fi
    
    # Determine which versions to remove
    keep_count=$RETENTION_COUNT
    removed_count=0
    
    for version in "${versions[@]}"; do
        # Always keep current and previous versions
        if echo "$protected_versions" | grep -qx "$version"; then
            log "  Keeping protected: ${version}"
            continue
        fi
        
        # Keep N most recent
        if [ $keep_count -gt 0 ]; then
            log "  Keeping recent: ${version}"
            ((keep_count--))
            continue
        fi
        
        # Remove this version
        version_path="${model_dir}/${version}"
        version_size=$(du -sh "$version_path" | cut -f1)
        
        log "  Removing old version: ${version} (size: ${version_size})"
        
        # Calculate size before removal
        size_bytes=$(du -sb "$version_path" | cut -f1)
        
        # Remove version directory
        rm -rf "$version_path"
        
        ((removed_count++))
        TOTAL_REMOVED=$((TOTAL_REMOVED + 1))
        TOTAL_SIZE_FREED=$((TOTAL_SIZE_FREED + size_bytes))
    done
    
    log "  Removed ${removed_count} versions for ${model_name}"
done

# Convert bytes to human-readable
human_size() {
    local bytes=$1
    if [ $bytes -ge 1073741824 ]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1073741824}")GB"
    elif [ $bytes -ge 1048576 ]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1048576}")MB"
    elif [ $bytes -ge 1024 ]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1024}")KB"
    else
        echo "${bytes}B"
    fi
}

SIZE_FREED=$(human_size $TOTAL_SIZE_FREED)

log ""
log "===== Cleanup completed ====="
log "Total versions removed: ${TOTAL_REMOVED}"
log "Total disk space freed: ${SIZE_FREED}"

exit 0
